# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'ShortVideo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ShortVideo

  pod 'PLShortVideoKit', '~> 3.2.4'
  pod 'Masonry'
  pod 'MMMaterialDesignSpinner'
  pod 'JGProgressHUD'
  pod 'SDWebImage'
  pod 'SDCycleScrollView','>= 1.80'
  pod 'SVProgressHUD'
  pod 'FURenderKit', '~> 8.3.0'
  
  
end
